"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import ThemeShell from "@/components/theme/ThemeShell";

type Category = { id:number; name:string; slug:string; parent:number };
type Uploaded = { id:string; url:string; filename:string };
const input = "mt-2 w-full rounded-xl border border-[#e0e6eb] bg-white px-4 py-3 text-sm outline-none transition focus:border-[#01A14B] focus:ring-4 focus:ring-[#01A14B]/10";
const label = "block text-sm font-bold text-[#111c2d]";

export default function CreateCampaignPage() {
  const [step,setStep]=useState(1); const [token,setToken]=useState(""); const [categories,setCategories]=useState<Category[]>([]);
  const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState(""); const [created,setCreated]=useState<{id:number;status:string}|null>(null);
  const [images,setImages]=useState<Uploaded[]>([]);
  const [form,setForm]=useState({title:"",description:"",story:"",category:"",sub_category:"",location:"",goal_amount:"",end_date:"",min_donation_amount:"5",max_donation_amount:"10000",suggested:"10,25,50,100"});
  const set=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}));
  useEffect(()=>{ const t=localStorage.getItem("access_token")||""; setToken(t); if(t) fetch("/api/campaigns/categories",{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.json()).then(d=>setCategories(Array.isArray(d?.data)?d.data:[])).catch(()=>{}); },[]);
  const parents=useMemo(()=>categories.filter(c=>c.parent===0),[categories]); const children=useMemo(()=>categories.filter(c=>c.parent===Number(form.category)),[categories,form.category]);
  async function upload(files:FileList|null){ if(!files?.length||!token)return; setUploading(true);setError(""); try{const fd=new FormData();Array.from(files).forEach(f=>fd.append("images[]",f));const r=await fetch("/api/campaigns/media",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:fd});const d=await r.json();if(!r.ok)throw new Error(d?.message||"Image upload failed.");setImages(x=>[...x,...(d.images||[])]);}catch(e){setError(e instanceof Error?e.message:"Image upload failed.");}finally{setUploading(false)} }
  function validate(s:number){if(s===1&&(!form.title.trim()||!form.description.trim()||!form.location.trim()||!form.category)){setError("Complete the required campaign details before continuing.");return false}if(s===2&&(!form.goal_amount||Number(form.goal_amount)<=0)){setError("Enter a fundraising goal greater than zero.");return false}if(s===3&&(!form.story.trim()||images.length===0)){setError("Add your campaign story and at least one image.");return false}setError("");return true}
  async function submit(e:FormEvent){e.preventDefault();if(!token){setError("Please sign in with a fundraiser account first.");return}if(!validate(3))return;setBusy(true);setError("");try{const suggested=form.suggested.split(",").map(x=>Number(x.trim())).filter(x=>x>0).map((amount,i)=>({amount,is_default:i===1,description:""}));const payload={title:form.title,description:form.description,story:form.story,images:images.map(x=>Number(x.id)),category:Number(form.category),sub_category:form.sub_category?Number(form.sub_category):0,location:form.location,end_date:form.end_date?`${form.end_date} 23:59:59`:undefined,has_goal:true,goal_type:"raised-amount",goal_amount:Number(form.goal_amount),reaching_action:"close",allow_custom_donation:true,min_donation_amount:form.min_donation_amount,max_donation_amount:form.max_donation_amount,suggested_option_type:"amount-only",suggested_options:suggested,status:"pending",tags:[],collaborators:[],show_collaborator_list:false,is_featured:false};const r=await fetch("/api/campaigns/create",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d?.message||Object.values(d?.data?.details||{}).flat().join(" ")||"Campaign creation failed.");setCreated(d.data);}catch(e){setError(e instanceof Error?e.message:"Campaign creation failed.");}finally{setBusy(false)}}
  if(!token)return <ThemeShell><main className="container-1218 py-16"><div className="mx-auto max-w-xl rounded-2xl border border-[#e0e6eb] bg-[#f8fafd] p-8 text-center"><h1 className="text-3xl font-extrabold">Create a campaign</h1><p className="mt-3 text-[#5a6a85]">Sign in with your fundraiser account before starting a campaign.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-[#01A14B] px-6 py-3 font-bold text-white">Sign in</Link></div></main></ThemeShell>;
  if(created)return <ThemeShell><main className="container-1218 py-16"><div className="mx-auto max-w-2xl rounded-3xl border border-[#d9eee2] bg-white p-8 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#e9f8ef] text-2xl text-[#01A14B]">✓</div><h1 className="mt-5 text-3xl font-extrabold">Campaign submitted</h1><p className="mt-3 text-[#5a6a85]">Campaign #{created.id} has been saved with status <b>{created.status}</b> and is ready for review.</p><Link href={`/campaign/${created.id}`} className="mt-6 inline-flex rounded-xl bg-[#01A14B] px-6 py-3 font-bold text-white">View campaign</Link></div></main></ThemeShell>;
  return <ThemeShell><main className="bg-[#f8fafd] py-10"><div className="container-1218"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-[#01A14B]">Fundraise on Hiilbox</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">Create your campaign</h1><p className="mt-2 text-[#5a6a85]">Tell your story, set your goal, add media, then submit it for review.</p></div><div className="mb-7 grid grid-cols-4 gap-2">{["Basics","Goal","Story & media","Review"].map((x,i)=><div key={x} className={`rounded-xl px-3 py-3 text-center text-xs font-bold sm:text-sm ${step>=i+1?"bg-[#01A14B] text-white":"bg-white text-[#5a6a85]"}`}>{i+1}. {x}</div>)}</div><form onSubmit={submit} className="rounded-3xl border border-[#e0e6eb] bg-white p-6 shadow-sm sm:p-8">{error&&<div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {step===1&&<div className="grid gap-6 sm:grid-cols-2"><div className="sm:col-span-2"><label className={label}>Campaign title *</label><input className={input} value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Help us build..."/></div><div className="sm:col-span-2"><label className={label}>Short description *</label><textarea className={input} rows={3} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="A clear summary of what you are raising money for."/></div><div><label className={label}>Category *</label><select className={input} value={form.category} onChange={e=>{set("category",e.target.value);set("sub_category","")}}><option value="">Choose category</option>{parents.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><label className={label}>Subcategory</label><select className={input} value={form.sub_category} onChange={e=>set("sub_category",e.target.value)}><option value="">None</option>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="sm:col-span-2"><label className={label}>Location *</label><input className={input} value={form.location} onChange={e=>set("location",e.target.value)} placeholder="Hargeisa, Somaliland"/></div></div>}
  {step===2&&<div className="grid gap-6 sm:grid-cols-2"><div><label className={label}>Fundraising goal (USD) *</label><input type="number" min="1" step="0.01" className={input} value={form.goal_amount} onChange={e=>set("goal_amount",e.target.value)}/></div><div><label className={label}>End date</label><input type="date" className={input} value={form.end_date} onChange={e=>set("end_date",e.target.value)}/></div><div><label className={label}>Minimum donation (USD)</label><input type="number" min="1" className={input} value={form.min_donation_amount} onChange={e=>set("min_donation_amount",e.target.value)}/></div><div><label className={label}>Maximum donation (USD)</label><input type="number" min="1" className={input} value={form.max_donation_amount} onChange={e=>set("max_donation_amount",e.target.value)}/></div><div className="sm:col-span-2"><label className={label}>Suggested donation amounts</label><input className={input} value={form.suggested} onChange={e=>set("suggested",e.target.value)} placeholder="10,25,50,100"/><p className="mt-2 text-xs text-[#5a6a85]">Comma-separated USD amounts.</p></div></div>}
  {step===3&&<div className="space-y-6"><div><label className={label}>Campaign story *</label><textarea className={input} rows={10} value={form.story} onChange={e=>set("story",e.target.value)} placeholder="Explain the need, who will benefit, how funds will be used, and why this matters."/></div><div><label className={label}>Campaign images *</label><input type="file" accept="image/*" multiple className={input} onChange={e=>upload(e.target.files)}/><p className="mt-2 text-xs text-[#5a6a85]">{uploading?"Uploading...":`${images.length} image(s) uploaded. The first image will be the campaign cover.`}</p>{images.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map(x=><div key={x.id} className="overflow-hidden rounded-xl border border-[#e0e6eb]"><img src={x.url} alt={x.filename} className="aspect-video h-full w-full object-cover"/></div>)}</div>}</div></div>}
  {step===4&&<div className="space-y-6"><div className="overflow-hidden rounded-2xl border border-[#e0e6eb]">{images[0]&&<img src={images[0].url} alt="Campaign cover" className="aspect-[16/7] w-full object-cover"/>}<div className="p-6"><p className="text-sm font-bold text-[#01A14B]">{parents.find(c=>c.id===Number(form.category))?.name||"Campaign"}</p><h2 className="mt-2 text-2xl font-extrabold">{form.title}</h2><p className="mt-3 text-[#5a6a85]">{form.description}</p><div className="mt-5 grid grid-cols-2 gap-4"><div><span className="text-xs text-[#5a6a85]">Goal</span><p className="font-bold">${Number(form.goal_amount||0).toLocaleString()}</p></div><div><span className="text-xs text-[#5a6a85]">Location</span><p className="font-bold">{form.location}</p></div></div></div></div><p className="rounded-xl bg-[#f8fafd] p-4 text-sm text-[#5a6a85]">Submitting sends this campaign for review. Fundraiser accounts cannot publish campaigns directly.</p></div>}
  <div className="mt-8 flex items-center justify-between border-t border-[#e0e6eb] pt-6"><button type="button" disabled={step===1||busy} onClick={()=>{setError("");setStep(s=>Math.max(1,s-1))}} className="rounded-xl border border-[#e0e6eb] px-5 py-3 font-bold disabled:opacity-40">Back</button>{step<4?<button type="button" onClick={()=>validate(step)&&setStep(s=>s+1)} className="rounded-xl bg-[#01A14B] px-6 py-3 font-bold text-white">Continue</button>:<button disabled={busy||uploading} className="rounded-xl bg-[#01A14B] px-6 py-3 font-bold text-white disabled:opacity-50">{busy?"Submitting...":"Submit campaign"}</button>}</div></form></div></main></ThemeShell>;
}
