import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import "@/utils/i18n";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "../components/ui/toaster";
import { CustomizerContextProvider } from "@/app/context/CustomizerContext";

import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MaterialM - Nextjs  Dashboard with ShadCN Ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        </head>
        <body className={`${inter.className}`}>
          <NextTopLoader color="#5d87ff" showSpinner={false} />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CustomizerContextProvider>{children}</CustomizerContextProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
